services:
  telethon-media-bot:
    image: ghcr.io/ccawmiku/telethon-bot-token-mtproto:latest
    container_name: telethon-media-bot
    restart: unless-stopped
    ports:
      - "8000:8000"
    volumes:
      - /opt/telethon-media-bot/downloads:/downloads
      - /opt/telethon-media-bot/sessions:/sessions
      - /opt/telethon-media-bot/config:/config
